version: '3.9'
services:
  consumidor-de-emails:
    build: .
    volumes: 
      - .env:/.env
  rabbit:
    image: rabbitmq:3.11-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
      - RABBITMQ_DEFAULT_VHOST=email
    ports:
      - 15672:15672/tcp
      - 5672:5672/tcp
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000/tcp
      - 9001:9001/tcp
    volumes:
      - minio:/data
  benchmarking:
    build: .
    volumes:
      - .env.benchmarking:/.env
    entrypoint: /benchmarking
volumes:
  minio: {}


