basePath: /
definitions:
  controllers.sent:
    properties:
      message:
        type: string
    type: object
  model.Email:
    properties:
      attachments:
        items:
          type: string
        type: array
      blindReceivers:
        items:
          $ref: '#/definitions/model.Receiver'
        minItems: 1
        type: array
      message:
        type: string
      receivers:
        items:
          $ref: '#/definitions/model.Receiver'
        minItems: 1
        type: array
      subject:
        type: string
      template:
        $ref: '#/definitions/model.TemplateData'
    required:
    - subject
    type: object
  model.Queue:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      dlx:
        type: string
      maxRetries:
        type: integer
      name:
        type: string
    type: object
  model.QueuePartial:
    properties:
      maxRetries:
        type: integer
      name:
        type: string
    required:
    - name
    type: object
  model.Receiver:
    properties:
      email:
        type: string
      name:
        type: string
    required:
    - email
    - name
    type: object
  model.Template:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      fields:
        items:
          type: string
        type: array
      name:
        type: string
      roles:
        items:
          type: string
        type: array
      template:
        type: string
    type: object
  model.TemplateData:
    properties:
      data:
        additionalProperties:
          type: string
        type: object
      name:
        type: string
    required:
    - name
    type: object
  model.TemplatePartial:
    properties:
      name:
        type: string
      roles:
        items:
          type: string
        type: array
      template:
        type: string
    required:
    - name
    - template
    type: object
  model.UserPartial:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is an api that publishes emails in RabbitMQ.
  title: Publisher Emails
  version: "1.0"
paths:
  /email/queue:
    get:
      consumes:
      - application/json
      description: Get all RabbitMQ queues.
      produces:
      - application/json
      responses:
        "200":
          description: all queues
          schema:
            items:
              $ref: '#/definitions/model.Queue'
            type: array
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Get queues
      tags:
      - queue
    post:
      consumes:
      - application/json
      description: Create a RabbitMQ queue with DLX.
      parameters:
      - description: queue params
        in: body
        name: queue
        required: true
        schema:
          $ref: '#/definitions/model.QueuePartial'
      produces:
      - application/json
      responses:
        "201":
          description: create queue successfully
          schema:
            $ref: '#/definitions/controllers.sent'
        "400":
          description: an invalid queue param was sent
          schema:
            $ref: '#/definitions/controllers.sent'
        "409":
          description: queue already exist
          schema:
            $ref: '#/definitions/controllers.sent'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Creating queue
      tags:
      - queue
  /email/queue/{name}:
    delete:
      consumes:
      - application/json
      description: Delete a queue with DLX.
      parameters:
      - description: queue name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: queue deleted
          schema:
            $ref: '#/definitions/controllers.sent'
        "404":
          description: queue dont exist
          schema:
            $ref: '#/definitions/controllers.sent'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Delete queues
      tags:
      - queue
  /email/queue/{name}/send:
    post:
      consumes:
      - application/json
      description: Sends an email to the RabbitMQ queue.
      parameters:
      - description: queue name
        in: path
        name: name
        required: true
        type: string
      - description: email
        in: body
        name: queue
        required: true
        schema:
          $ref: '#/definitions/model.Email'
      produces:
      - application/json
      responses:
        "200":
          description: email sent successfully
          schema:
            $ref: '#/definitions/controllers.sent'
        "400":
          description: an invalid email param was sent
          schema:
            $ref: '#/definitions/controllers.sent'
        "404":
          description: queue does not exist
          schema:
            $ref: '#/definitions/controllers.sent'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Sends email
      tags:
      - queue
  /email/template:
    get:
      consumes:
      - application/json
      description: Delete all email templates.
      produces:
      - application/json
      responses:
        "200":
          description: all templates
          schema:
            items:
              $ref: '#/definitions/model.Template'
            type: array
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Get templates
      tags:
      - template
    post:
      consumes:
      - application/json
      description: Create a email template.
      parameters:
      - description: template params
        in: body
        name: template
        required: true
        schema:
          $ref: '#/definitions/model.TemplatePartial'
      produces:
      - application/json
      responses:
        "201":
          description: create template successfully
          schema:
            $ref: '#/definitions/controllers.sent'
        "400":
          description: an invalid template param was sent
          schema:
            $ref: '#/definitions/controllers.sent'
        "409":
          description: template name already exist
          schema:
            $ref: '#/definitions/controllers.sent'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Creating template
      tags:
      - template
  /email/template/{name}:
    delete:
      consumes:
      - application/json
      description: Delete a email template.
      parameters:
      - description: template name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: template deleted
          schema:
            $ref: '#/definitions/controllers.sent'
        "404":
          description: template does not exist
          schema:
            $ref: '#/definitions/controllers.sent'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Delete template
      tags:
      - template
    get:
      consumes:
      - application/json
      description: Get a email template.
      parameters:
      - description: template name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: all templates
          schema:
            $ref: '#/definitions/model.Template'
        "404":
          description: template does not exist
          schema:
            items:
              $ref: '#/definitions/controllers.sent'
            type: array
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Get template
      tags:
      - template
    put:
      consumes:
      - application/json
      description: Update a email template.
      parameters:
      - description: template name
        in: path
        name: name
        required: true
        type: string
      - description: template params
        in: body
        name: template
        required: true
        schema:
          $ref: '#/definitions/model.TemplatePartial'
      produces:
      - application/json
      responses:
        "200":
          description: template updated
          schema:
            $ref: '#/definitions/controllers.sent'
        "400":
          description: an invalid template param was sent
          schema:
            $ref: '#/definitions/controllers.sent'
        "404":
          description: template does not exist
          schema:
            $ref: '#/definitions/controllers.sent'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Update template
      tags:
      - template
  /user:
    delete:
      consumes:
      - application/json
      description: Delete current user.
      produces:
      - application/json
      responses:
        "200":
          description: user deleted
          schema:
            $ref: '#/definitions/controllers.sent'
        "401":
          description: unathorized
          schema:
            $ref: '#/definitions/controllers.sent'
        "404":
          description: user dont exist
          schema:
            $ref: '#/definitions/controllers.sent'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Delete user
      tags:
      - user
    get:
      consumes:
      - application/json
      description: Get current user informatios.
      produces:
      - application/json
      responses:
        "200":
          description: user informations
          schema:
            $ref: '#/definitions/controllers.sent'
        "401":
          description: unathorized
          schema:
            $ref: '#/definitions/controllers.sent'
        "404":
          description: user does not exist
          schema:
            $ref: '#/definitions/controllers.sent'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Get user
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Create a user in application.
      parameters:
      - description: user params
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserPartial'
      produces:
      - application/json
      responses:
        "201":
          description: user created successfully
          schema:
            $ref: '#/definitions/controllers.sent'
        "400":
          description: an invalid user param was sent
          schema:
            $ref: '#/definitions/controllers.sent'
        "409":
          description: user already exist
          schema:
            $ref: '#/definitions/controllers.sent'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Create user
      tags:
      - user
    put:
      consumes:
      - application/json
      description: Update user informatios.
      parameters:
      - description: user params
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserPartial'
      produces:
      - application/json
      responses:
        "200":
          description: user updated
          schema:
            $ref: '#/definitions/controllers.sent'
        "400":
          description: an invalid user param was sent
          schema:
            $ref: '#/definitions/controllers.sent'
        "401":
          description: unathorized
          schema:
            $ref: '#/definitions/controllers.sent'
        "404":
          description: user does not exist
          schema:
            $ref: '#/definitions/controllers.sent'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Update user
      tags:
      - user
  /user/session:
    post:
      consumes:
      - application/json
      description: Create a user session and set in the response cookie.
      parameters:
      - description: user params
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserPartial'
      produces:
      - application/json
      responses:
        "201":
          description: session created successfully
          schema:
            $ref: '#/definitions/controllers.sent'
        "400":
          description: an invalid user param was sent
          schema:
            $ref: '#/definitions/controllers.sent'
        "404":
          description: user does not exist
          schema:
            $ref: '#/definitions/controllers.sent'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Create session
      tags:
      - user
    put:
      consumes:
      - application/json
      description: Refresh a user session and set in the response cookie.
      produces:
      - application/json
      responses:
        "200":
          description: session refreshed successfully
          schema:
            $ref: '#/definitions/controllers.sent'
        "401":
          description: session does not exist
          schema:
            $ref: '#/definitions/controllers.sent'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/controllers.sent'
      summary: Refresh session
      tags:
      - user
swagger: "2.0"
