global:
  scrape_interval:     500ms
  evaluation_interval: 500ms
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090']

  - job_name: 'consumidor-de-emails'
    static_configs:
      - targets: ['consumidor-de-emails:8001']
